import AdminSidebar from "@/components/shared/AdminSidebar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="flex flex-row">
      <AdminSidebar/>
      <section className="admin-container px-1">
        <div className="w-full max-w-full">
          {children}
        </div>
      </section>
    </main>
  )
}
